// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzhmvmnaOMN7OfVg9yQYrSw1X3D1Ct6H4',
    appId: '1:435253691019:web:e19827acf8f4f563d30a8e',
    messagingSenderId: '435253691019',
    projectId: 'otopark-sistemi-cd3ec',
    authDomain: 'otopark-sistemi-cd3ec.firebaseapp.com',
    storageBucket: 'otopark-sistemi-cd3ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4cfu2FYYf_NJgoaj5D0t9L48sRA1rC5k',
    appId: '1:435253691019:android:9c266f128b94751bd30a8e',
    messagingSenderId: '435253691019',
    projectId: 'otopark-sistemi-cd3ec',
    storageBucket: 'otopark-sistemi-cd3ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1aPOh402k29JFa_GSp-kgnt2npGuu-A',
    appId: '1:435253691019:ios:3a68a8afbbb5cf49d30a8e',
    messagingSenderId: '435253691019',
    projectId: 'otopark-sistemi-cd3ec',
    storageBucket: 'otopark-sistemi-cd3ec.firebasestorage.app',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1aPOh402k29JFa_GSp-kgnt2npGuu-A',
    appId: '1:435253691019:ios:3a68a8afbbb5cf49d30a8e',
    messagingSenderId: '435253691019',
    projectId: 'otopark-sistemi-cd3ec',
    storageBucket: 'otopark-sistemi-cd3ec.firebasestorage.app',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzhmvmnaOMN7OfVg9yQYrSw1X3D1Ct6H4',
    appId: '1:435253691019:web:d8855af94f4b1ba6d30a8e',
    messagingSenderId: '435253691019',
    projectId: 'otopark-sistemi-cd3ec',
    authDomain: 'otopark-sistemi-cd3ec.firebaseapp.com',
    storageBucket: 'otopark-sistemi-cd3ec.firebasestorage.app',
  );
}
